site_name: Super Chasm Hunter
strict: true
repo_url: https://github.com/FilippoGurioli/super-chasm-hunter-pm
theme:
  name: material
  # favicon: assets/logo.svg
  language: it
  # logo: assets/logo.svg
  icon:
    repo: material/github

  features:
    - search.suggest
    - navigation.top
    - navigation.footer
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# extra_css:
#   - assets/extra.css

plugins:
  - search
  - awesome-nav

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

